import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", ".marketing-theme-dark"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "Inter", "system-ui", "Segoe UI", "Roboto", "sans-serif"],
        admin: ["Roboto", "DM Sans", "Inter", "system-ui", "Segoe UI", "sans-serif"],
      },
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground": "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground": "hsl(var(--destructive-foreground) / <alpha-value>)",
        "mkt-bg": "rgb(var(--mkt-bg) / <alpha-value>)",
        "mkt-bg-secondary": "rgb(var(--mkt-bg-secondary) / <alpha-value>)",
        "mkt-card": "rgb(var(--mkt-card) / <alpha-value>)",
        "mkt-border": "rgb(var(--mkt-border) / <alpha-value>)",
        "mkt-text": "rgb(var(--mkt-text) / <alpha-value>)",
        "mkt-text-secondary": "rgb(var(--mkt-text-secondary) / <alpha-value>)",
        "mkt-nav": "rgb(var(--mkt-nav) / <alpha-value>)",
        "mkt-footer": "rgb(var(--mkt-footer) / <alpha-value>)",
        waka: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          300: "#fdba74",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
          800: "#9a3412",
          900: "#7c2d12",
          950: "#431407",
        },
      },
      boxShadow: {
        waka: "0 1px 2px rgb(28 25 23 / 0.06), 0 8px 24px rgb(234 88 12 / 0.08)",
        "waka-sm": "0 1px 2px rgb(28 25 23 / 0.05), 0 4px 12px rgb(234 88 12 / 0.06)",
        mkt: "0 1px 2px rgb(var(--mkt-shadow) / 0.06), 0 4px 16px rgb(var(--mkt-shadow) / 0.05)",
        "mkt-lg": "0 8px 32px rgb(var(--mkt-shadow) / 0.12), 0 2px 8px rgb(var(--mkt-shadow) / 0.06)",
      },
    },
  },
  plugins: [],
} satisfies Config;
