import type { Config } from "tailwindcss";

const semanticColor = (name: string) => `hsl(var(--${name}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", ".dark", ".marketing-theme-dark"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "Inter", "system-ui", "Segoe UI", "Roboto", "sans-serif"],
        admin: ["Roboto", "DM Sans", "Inter", "system-ui", "Segoe UI", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
      },
      colors: {
        background: semanticColor("background"),
        foreground: semanticColor("foreground"),
        card: semanticColor("card"),
        "card-foreground": semanticColor("card-foreground"),
        primary: semanticColor("primary"),
        "primary-foreground": semanticColor("primary-foreground"),
        "primary-hover": semanticColor("primary-hover"),
        secondary: semanticColor("secondary"),
        "secondary-foreground": semanticColor("secondary-foreground"),
        muted: semanticColor("muted"),
        "muted-foreground": semanticColor("muted-foreground"),
        border: semanticColor("border"),
        input: semanticColor("input"),
        ring: semanticColor("ring"),
        destructive: semanticColor("destructive"),
        "destructive-foreground": semanticColor("destructive-foreground"),
        surface: semanticColor("surface"),
        "surface-foreground": semanticColor("surface-foreground"),
        "surface-elevated": semanticColor("surface-elevated"),
        "surface-muted": semanticColor("surface-muted"),
        dialog: semanticColor("dialog"),
        "dialog-foreground": semanticColor("dialog-foreground"),
        divider: semanticColor("divider"),
        "text-primary": semanticColor("text-primary"),
        "text-secondary": semanticColor("text-secondary"),
        "text-muted": semanticColor("text-muted"),
        "text-inverse": semanticColor("text-inverse"),
        overlay: semanticColor("overlay"),
        focus: semanticColor("focus"),
        disabled: semanticColor("disabled"),
        selection: semanticColor("selection"),
        success: semanticColor("success"),
        "success-foreground": semanticColor("success-foreground"),
        "success-muted": semanticColor("success-muted"),
        warning: semanticColor("warning"),
        "warning-foreground": semanticColor("warning-foreground"),
        "warning-muted": semanticColor("warning-muted"),
        danger: semanticColor("danger"),
        "danger-foreground": semanticColor("danger-foreground"),
        "danger-muted": semanticColor("danger-muted"),
        info: semanticColor("info"),
        "info-foreground": semanticColor("info-foreground"),
        "info-muted": semanticColor("info-muted"),
        pending: semanticColor("pending"),
        "pending-foreground": semanticColor("pending-foreground"),
        "pending-muted": semanticColor("pending-muted"),
        draft: semanticColor("draft"),
        "draft-foreground": semanticColor("draft-foreground"),
        "draft-muted": semanticColor("draft-muted"),
        trial: semanticColor("trial"),
        "trial-foreground": semanticColor("trial-foreground"),
        "trial-muted": semanticColor("trial-muted"),
        expired: semanticColor("expired"),
        "expired-foreground": semanticColor("expired-foreground"),
        "expired-muted": semanticColor("expired-muted"),
        offline: semanticColor("offline"),
        "offline-foreground": semanticColor("offline-foreground"),
        "offline-muted": semanticColor("offline-muted"),
        syncing: semanticColor("syncing"),
        "syncing-foreground": semanticColor("syncing-foreground"),
        "syncing-muted": semanticColor("syncing-muted"),
        paid: semanticColor("paid"),
        "paid-foreground": semanticColor("paid-foreground"),
        "paid-muted": semanticColor("paid-muted"),
        free: semanticColor("free"),
        "free-foreground": semanticColor("free-foreground"),
        "free-muted": semanticColor("free-muted"),
        business: semanticColor("business"),
        "business-foreground": semanticColor("business-foreground"),
        "business-muted": semanticColor("business-muted"),
        vip: semanticColor("vip"),
        "vip-foreground": semanticColor("vip-foreground"),
        "vip-muted": semanticColor("vip-muted"),
        cancelled: semanticColor("cancelled"),
        "cancelled-foreground": semanticColor("cancelled-foreground"),
        "cancelled-muted": semanticColor("cancelled-muted"),
        active: semanticColor("active"),
        "active-foreground": semanticColor("active-foreground"),
        "active-muted": semanticColor("active-muted"),
        chart: {
          grid: semanticColor("chart-grid"),
          axis: semanticColor("chart-axis"),
          label: semanticColor("chart-label"),
          primary: semanticColor("chart-primary"),
          secondary: semanticColor("chart-secondary"),
          positive: semanticColor("chart-positive"),
          negative: semanticColor("chart-negative"),
          warning: semanticColor("chart-warning"),
          neutral: semanticColor("chart-neutral"),
          bg: semanticColor("chart-bg"),
          hover: semanticColor("chart-hover"),
          selection: semanticColor("chart-selection"),
          track: semanticColor("chart-track"),
          "dot-stroke": semanticColor("chart-dot-stroke"),
          "series-1": semanticColor("chart-series-1"),
          "series-2": semanticColor("chart-series-2"),
          "series-3": semanticColor("chart-series-3"),
          "series-4": semanticColor("chart-series-4"),
          "series-5": semanticColor("chart-series-5"),
        },
        "mkt-bg": "rgb(var(--mkt-bg) / <alpha-value>)",
        "mkt-bg-secondary": "rgb(var(--mkt-bg-secondary) / <alpha-value>)",
        "mkt-card": "rgb(var(--mkt-card) / <alpha-value>)",
        "mkt-border": "rgb(var(--mkt-border) / <alpha-value>)",
        "mkt-text": "rgb(var(--mkt-text) / <alpha-value>)",
        "mkt-text-secondary": "rgb(var(--mkt-text-secondary) / <alpha-value>)",
        "mkt-nav": "rgb(var(--mkt-nav) / <alpha-value>)",
        "mkt-footer": "rgb(var(--mkt-footer) / <alpha-value>)",
        brand: {
          orange: "#f97316",
          "orange-dark": "#ea580c",
          cream: "#fffaf5",
          "cream-wash": "#faf7f4",
        },
        waka: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          300: "#fdba74",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
          800: "#9a3412",
          900: "#7c2d12",
          950: "#431407",
        },
        /** Legacy stone utilities → semantic tokens (Phase 17.9 universal bridge) */
        stone: {
          50: semanticColor("muted"),
          100: semanticColor("muted"),
          200: semanticColor("border"),
          300: semanticColor("border"),
          400: semanticColor("muted-foreground"),
          500: semanticColor("muted-foreground"),
          600: semanticColor("muted-foreground"),
          700: semanticColor("muted-foreground"),
          800: semanticColor("foreground"),
          900: semanticColor("foreground"),
          950: semanticColor("foreground"),
        },
        slate: {
          50: semanticColor("muted"),
          100: semanticColor("muted"),
          200: semanticColor("border"),
          300: semanticColor("border"),
          400: semanticColor("muted-foreground"),
          500: semanticColor("muted-foreground"),
          600: semanticColor("muted-foreground"),
          700: semanticColor("muted-foreground"),
          800: semanticColor("foreground"),
          900: semanticColor("foreground"),
          950: semanticColor("foreground"),
        },
        gray: {
          50: semanticColor("muted"),
          100: semanticColor("muted"),
          200: semanticColor("border"),
          300: semanticColor("border"),
          400: semanticColor("muted-foreground"),
          500: semanticColor("muted-foreground"),
          600: semanticColor("muted-foreground"),
          700: semanticColor("muted-foreground"),
          800: semanticColor("foreground"),
          900: semanticColor("foreground"),
          950: semanticColor("foreground"),
        },
      },
      boxShadow: {
        waka: "0 1px 2px rgb(28 25 23 / 0.06), 0 8px 24px rgb(234 88 12 / 0.08)",
        "waka-sm": "0 1px 2px rgb(28 25 23 / 0.05), 0 4px 12px rgb(234 88 12 / 0.06)",
        mkt: "0 1px 2px rgb(var(--mkt-shadow) / 0.06), 0 4px 16px rgb(var(--mkt-shadow) / 0.05)",
        "mkt-lg": "0 8px 32px rgb(var(--mkt-shadow) / 0.12), 0 2px 8px rgb(var(--mkt-shadow) / 0.06)",
      },
      keyframes: {
        "pin-shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "20%, 60%": { transform: "translateX(-6px)" },
          "40%, 80%": { transform: "translateX(6px)" },
        },
      },
      animation: {
        "pin-shake": "pin-shake 0.4s ease-in-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
