/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalWakaRouteImport } from './routes/internal.waka'
import { Route as AuthRecoveryRouteImport } from './routes/auth.recovery'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOfficeRouteImport } from './routes/_authenticated/office'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDayCloseRouteImport } from './routes/_authenticated/day-close'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as InternalWakaAdminsRouteImport } from './routes/internal.waka.admins'
import { Route as InternalWakaActivationsRouteImport } from './routes/internal.waka.activations'
import { Route as InternalWakaShopShopIdRouteImport } from './routes/internal.waka.shop.$shopId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalWakaRoute = InternalWakaRouteImport.update({
  id: '/internal/waka',
  path: '/internal/waka',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfficeRoute = AuthenticatedOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDayCloseRoute = AuthenticatedDayCloseRouteImport.update({
  id: '/day-close',
  path: '/day-close',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InternalWakaAdminsRoute = InternalWakaAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => InternalWakaRoute,
} as any)
const InternalWakaActivationsRoute = InternalWakaActivationsRouteImport.update({
  id: '/activations',
  path: '/activations',
  getParentRoute: () => InternalWakaRoute,
} as any)
const InternalWakaShopShopIdRoute = InternalWakaShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => InternalWakaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder': typeof FounderRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/day-close': typeof AuthenticatedDayCloseRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/products': typeof AuthenticatedProductsRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/internal/waka': typeof InternalWakaRouteWithChildren
  '/internal/waka/activations': typeof InternalWakaActivationsRoute
  '/internal/waka/admins': typeof InternalWakaAdminsRoute
  '/internal/waka/shop/$shopId': typeof InternalWakaShopShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder': typeof FounderRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/day-close': typeof AuthenticatedDayCloseRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/products': typeof AuthenticatedProductsRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/internal/waka': typeof InternalWakaRouteWithChildren
  '/internal/waka/activations': typeof InternalWakaActivationsRoute
  '/internal/waka/admins': typeof InternalWakaAdminsRoute
  '/internal/waka/shop/$shopId': typeof InternalWakaShopShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/founder': typeof FounderRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/day-close': typeof AuthenticatedDayCloseRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/office': typeof AuthenticatedOfficeRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/internal/waka': typeof InternalWakaRouteWithChildren
  '/internal/waka/activations': typeof InternalWakaActivationsRoute
  '/internal/waka/admins': typeof InternalWakaAdminsRoute
  '/internal/waka/shop/$shopId': typeof InternalWakaShopShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/company'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/founder'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/day-close'
    | '/expenses'
    | '/office'
    | '/products'
    | '/receipts'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/suppliers'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/recovery'
    | '/internal/waka'
    | '/internal/waka/activations'
    | '/internal/waka/admins'
    | '/internal/waka/shop/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/company'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/founder'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/customers'
    | '/dashboard'
    | '/day-close'
    | '/expenses'
    | '/office'
    | '/products'
    | '/receipts'
    | '/reports'
    | '/sell'
    | '/settings'
    | '/suppliers'
    | '/upgrade'
    | '/auth/callback'
    | '/auth/recovery'
    | '/internal/waka'
    | '/internal/waka/activations'
    | '/internal/waka/admins'
    | '/internal/waka/shop/$shopId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/acceptable-use'
    | '/company'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/founder'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/support'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/day-close'
    | '/_authenticated/expenses'
    | '/_authenticated/office'
    | '/_authenticated/products'
    | '/_authenticated/receipts'
    | '/_authenticated/reports'
    | '/_authenticated/sell'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/upgrade'
    | '/auth/callback'
    | '/auth/recovery'
    | '/internal/waka'
    | '/internal/waka/activations'
    | '/internal/waka/admins'
    | '/internal/waka/shop/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FounderRoute: typeof FounderRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  InternalWakaRoute: typeof InternalWakaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/waka': {
      id: '/internal/waka'
      path: '/internal/waka'
      fullPath: '/internal/waka'
      preLoaderRoute: typeof InternalWakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/office': {
      id: '/_authenticated/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof AuthenticatedOfficeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/day-close': {
      id: '/_authenticated/day-close'
      path: '/day-close'
      fullPath: '/day-close'
      preLoaderRoute: typeof AuthenticatedDayCloseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/internal/waka/admins': {
      id: '/internal/waka/admins'
      path: '/admins'
      fullPath: '/internal/waka/admins'
      preLoaderRoute: typeof InternalWakaAdminsRouteImport
      parentRoute: typeof InternalWakaRoute
    }
    '/internal/waka/activations': {
      id: '/internal/waka/activations'
      path: '/activations'
      fullPath: '/internal/waka/activations'
      preLoaderRoute: typeof InternalWakaActivationsRouteImport
      parentRoute: typeof InternalWakaRoute
    }
    '/internal/waka/shop/$shopId': {
      id: '/internal/waka/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/internal/waka/shop/$shopId'
      preLoaderRoute: typeof InternalWakaShopShopIdRouteImport
      parentRoute: typeof InternalWakaRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDayCloseRoute: typeof AuthenticatedDayCloseRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedOfficeRoute: typeof AuthenticatedOfficeRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDayCloseRoute: AuthenticatedDayCloseRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedOfficeRoute: AuthenticatedOfficeRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface InternalWakaRouteChildren {
  InternalWakaActivationsRoute: typeof InternalWakaActivationsRoute
  InternalWakaAdminsRoute: typeof InternalWakaAdminsRoute
  InternalWakaShopShopIdRoute: typeof InternalWakaShopShopIdRoute
}

const InternalWakaRouteChildren: InternalWakaRouteChildren = {
  InternalWakaActivationsRoute: InternalWakaActivationsRoute,
  InternalWakaAdminsRoute: InternalWakaAdminsRoute,
  InternalWakaShopShopIdRoute: InternalWakaShopShopIdRoute,
}

const InternalWakaRouteWithChildren = InternalWakaRoute._addFileChildren(
  InternalWakaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FounderRoute: FounderRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  InternalWakaRoute: InternalWakaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
